apiVersion: v2
name: loki
description: Loki Stack for centralized logging
type: application
version: 1.0.0
appVersion: "2.9.0"

dependencies:
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
