apiVersion: v2
name: metrics-server
description: Metrics Server for Kubernetes HPA
type: application
version: 1.0.0
appVersion: "0.7.0"

dependencies:
  - name: metrics-server
    version: 3.12.1
    repository: https://kubernetes-sigs.github.io/metrics-server/
