apiVersion: v2
name: argocd
description: ArgoCD GitOps continuous delivery tool
type: application
version: 1.0.0
appVersion: "2.10.0"

dependencies:
  - name: argo-cd
    version: 6.7.0
    repository: https://argoproj.github.io/argo-helm
